name: Run Frontend Tests
run-name: ${{ github.actor }} is running Frontend tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend
